version: "3"
services:

  frontend_main:
    container_name: ${SERVICE_NAME}
    tty: true
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - /${SERVICE_NAME}/node_modules
      - .:/${SERVICE_NAME}
    ports:
      - ${FRONTEND_PORT}:5001
    restart: on-failure
    environment:
      - CHOKIDAR_USEPOLLING=true
